---
- name: nginx 배포하기
  hosts: all
  become: yes
  
  tasks:
    - name: nginx
      shell: docker service create --name mynginx --replicas 3 --constraint node.role==worker --with-registry-auth -p 8008:80 nginx
